src/baldr/directededge.cc
valhalla/baldr/directededge.h

Need to know if directed edge is forward or reverse when accessing EdgeInfo/shape.

Add forward flag to directededge

---

src/baldr/edgeinfo.cc
src/baldr/graphtile.cc
valhalla/baldr/edgeinfo.h

Added GetShapePoint and SetPointers

---

valhalla/baldr/directededge.h

Fix size of Access fields.

---

src/baldr/edgeinfo.cc
src/baldr/graphtile.cc
valhalla/baldr/edgeinfo.h
valhalla/baldr/graphtile.h

@kevinkreiser - Thanks for pairing!
@dnesbitt61 @gknisely

Fixed edgeinfo index issue

---

src/baldr/edgeinfo.cc
src/baldr/graphtile.cc
valhalla/baldr/edgeinfo.h

removed the nodes from edgeinfo and reduced text offset sizes

---

src/baldr/location.cc
src/baldr/tilehierarchy.cc
test/location.cc
test/tilehierarchy.cc

reflecting changes in midgard pr: https://github.com/valhalla/midgard/pull/6

updates for ll class to be lon/lat

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h

@dgearhart @dnesbitt61 @kevinkreiser

link was missing.

---

src/baldr/graphtile.cc
valhalla/baldr/graphtile.h

Add the edgeinfo and textlist sizes (move them from builder class).

---

src/baldr/edgeinfo.cc
src/baldr/graphid.cc
src/baldr/graphtile.cc
valhalla/baldr/edgeinfo.h
valhalla/baldr/graphid.h

update edgeinfo to remove extra stuff and make use of encoded shape. shape will be cached once decoded the first time and wont be decoded until asked for

edgeinfo to use compressed shape

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h

Add hierarchy transitions and shortcut flags. Change lanes to lanecount.

---

src/baldr/directededge.cc
src/baldr/nodeinfo.cc
valhalla/baldr/directededge.h
valhalla/baldr/nodeinfo.h

so the class is polymorphic and can cast to derived (builder) classes

Add virtual destructors 

---

src/baldr/graphreader.cc
src/baldr/graphtile.cc
src/baldr/nodeinfo.cc
valhalla/baldr/graphreader.h
valhalla/baldr/nodeinfo.h

Use 3 bits and use RoadClass enum in the access methods. Add a method to test if a tile exists.

Fix best road class for a node.

---

src/baldr/directededge.cc

@kevinkreiser @gknisely @dgearhart

Initialize data.

---

valhalla/baldr/nodeinfo.h

Create constants for max. edges per tile and max. edges per node.
Need to recreate data once this is merged.

Increase edge_index. 

---

src/baldr/location.cc
src/baldr/pathlocation.cc
valhalla/baldr/location.h
valhalla/baldr/pathlocation.h

this adds the ability to set the point to which loki (for example) correlated the location when creating the pathlocation. previously this information wasn't available.

location and path location updates

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h

Use 24 bits (free some space for other attributes).

Change length to meters.

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h
valhalla/baldr/graphconstants.h

@dgearhart @dnesbitt61 @kevinkreiser

added cycle_lane and surface.

---

src/baldr/directededge.cc
valhalla/baldr/graphconstants.h

@dgearhart @dnesbitt61 @kevinkreiser

updated unpaved function.  Is based on surface now.

---

src/baldr/graphtile.cc

to see this you'd need to build baldr after configuring with CPPFLAGS="-DLOGGING_DEBUG"

log disk cache misses with debug only

---

valhalla/baldr/edgeinfo.h

and add a maximum value (so we can check in the builder).

Increase size of encoded shape

---

src/baldr/directededge.cc
src/baldr/graphid.cc
src/baldr/graphtile.cc
src/baldr/graphtileheader.cc
src/baldr/nodeinfo.cc
valhalla/baldr/directededge.h
valhalla/baldr/graphid.h
valhalla/baldr/graphtileheader.h
valhalla/baldr/nodeinfo.h

@dgearhart @dnesbitt61 @kevinkreiser 
Still need to figure out how to implement in the edgeinfo class as the constructor takes a ptr.  
This version logic can determine when you take a bit(s) from the spare bits and update the structure.  Also, it can determine if you add a member var to the class.  What it can't do, is determine if changed the order of the bitfields in the struct.  
Logic for bitfields is, negate and find the index of the most significant bit to get the "size". Finally, combine it to the seed.

Gk version

---

valhalla/baldr/graphconstants.h

@kevinkreiser @dnesbitt61 @dgearhart 
Nothing fancy....just basically an fyi

track is now a use.

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h

In preparation for trying to derive this during graph building. Just used a bit in a spare field so should not require rebuilding graph tiles.

Add internal flag to directed edge.

---

Makefile.am
src/baldr/exitsigninfo.cc
valhalla/baldr/exitsigninfo.h

Added ExitSignInfo

---

src/baldr/edgeinfo.cc
src/baldr/graphtile.cc
valhalla/baldr/edgeinfo.h
valhalla/baldr/graphtile.h

Initial exit info

---

valhalla/baldr/exitsign.h

Set size on the ExitSign::Type  enum

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h

@dgearhart @kevinkreiser @dnesbitt61

added exit bit.

---

src/baldr/edgeinfo.cc
src/baldr/graphreader.cc
src/baldr/graphtile.cc
valhalla/baldr/edgeinfo.h
valhalla/baldr/graphreader.h
valhalla/baldr/graphtile.h

these are supposed to be readonly classes so i wanted to make sure their interface was true to that.

constify graphtile and edgeinfo

---

.gitignore
Makefile.am
src/baldr/location.cc
test/location.cc
test/nodeinfo.cc
valhalla/baldr/location.h

also add nodeinfo test for @dnesbitt61

add address info to csv parsing

---

src/baldr/nodeinfo.cc
valhalla/baldr/nodeinfo.h

Change to use std::pair of floats but cast toPointLL in read access method.

Change internal storage of lat,lng 

---

src/baldr/graphid.cc
valhalla/baldr/graphid.h

i was sick of having to call set with all the parameters when all i wanted was to just set the damned id of the element within the tile. i let all of the method accessors so as to minimize diffs (except value because its at the top level of the object). prs for others coming up

simplify the graphid interface

---

src/baldr/signinfo.cc
valhalla/baldr/signinfo.h

@kevinkreiser @dnesbitt61 @gknisely

Updated includes and comments

---

src/baldr/nodeinfo.cc
valhalla/baldr/nodeinfo.h

Add some future attributes (commented out for now).

Increase max. number of edges per node. 

---

src/baldr/directededge.cc
src/baldr/nodeinfo.cc
valhalla/baldr/directededge.h
valhalla/baldr/graphconstants.h
valhalla/baldr/nodeinfo.h

Add new fields for growth.

---

src/baldr/nodeinfo.cc
valhalla/baldr/graphconstants.h
valhalla/baldr/nodeinfo.h

Add IntersectionType, local_driveable (count). Fix spare so size of type... was incorrect (was 1 bit too large!).

Fix size of type_

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h
valhalla/baldr/graphconstants.h

mjolnir and thor PRs to follow.

Update directed edge to add fields for "growth"

---

.gitignore
Makefile.am
test/directededge.cc
valhalla/baldr/directededge.h
valhalla/baldr/graphconstants.h

Add some explicit values to enums in graphconstants and add documentation/comments

Add directed edge test

---

src/baldr/nodeinfo.cc

@dgearhart @kevinkreiser  @dnesbitt61

internal version updates for nodeinfo.

---

valhalla/baldr/graphconstants.h

Increased kMaxTurnChannelLength to 200 meters

---

src/baldr/turn.cc
valhalla/baldr/turn.h

Updated odin and tests to follow

Added turn type

---

Makefile.am
src/baldr/turn.cc
test/turn.cc
valhalla/baldr/turn.h

Added GetType test and makefile updates

---

src/baldr/directededge.cc
test/directededge.cc
valhalla/baldr/directededge.h

turn types, stop impact, name consistency, opp local edge index.

Add data and methods for edge transition logic

---

src/baldr/tilehierarchy.cc
test/tilehierarchy.cc
valhalla/baldr/graphconstants.h

Service and Other are now combined at the lowest classification

Change RoadClass to separate Tertiary and Unclassified. 

---

src/baldr/nodeinfo.cc
valhalla/baldr/nodeinfo.h

(for how many edge heading/name consistency are stored)

Change local driveable to local_edge_count 

---

src/baldr/nodeinfo.cc
valhalla/baldr/nodeinfo.h

heading is reduced/expanded to 8 bits

---

src/baldr/nodeinfo.cc

rounding when expanding heading

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h

Separate "hierarchy" info into its own structure.

Change shortcut and superseded to a mask.

---

.gitignore
Makefile.am
src/baldr/streetname.cc
src/baldr/streetnames.cc
test/streetname.cc
test/streetnames.cc
valhalla/baldr/streetname.h
valhalla/baldr/streetnames.h

moved StreetName and StreetNames from odin to baldr

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h
valhalla/baldr/edgeinfo.h

Also update the max encoded shape size.

Add ctry crossing flag

---

Makefile.am
src/baldr/transitroute.cc
src/baldr/transitstop.cc
valhalla/baldr/transitroute.h
valhalla/baldr/transitstop.h

Not used for path finding but for trip path building.

Add transit stops and routes.

---

Makefile.am
src/baldr/transitdeparture.cc
valhalla/baldr/transitdeparture.h

Fixed size. Still needs some date/time definitions, trying to make them small enough to compress easily yet still allow easy lookup.

Transit departures

---

Makefile.am
src/baldr/transitcalendar.cc
src/baldr/transitdeparture.cc
src/baldr/transitroute.cc
src/baldr/transitstop.cc
src/baldr/transittransfer.cc
src/baldr/transittrip.cc
valhalla/baldr/graphconstants.h
valhalla/baldr/transitcalendar.h
valhalla/baldr/transitdeparture.h
valhalla/baldr/transitroute.h
valhalla/baldr/transitstop.h
valhalla/baldr/transittransfer.h
valhalla/baldr/transittrip.h

Moved a couple things into graphconstants. Nothing is actually in the graph tile or graphtile header yet, just putting in some base structures.

More transit structure additions.

---

src/baldr/transitcalendar.cc
src/baldr/transitdeparture.cc
src/baldr/transitroute.cc
src/baldr/transitstop.cc
src/baldr/transittransfer.cc
src/baldr/transittrip.cc
valhalla/baldr/transitcalendar.h
valhalla/baldr/transitdeparture.h
valhalla/baldr/transitroute.h
valhalla/baldr/transitstop.h
valhalla/baldr/transittransfer.h
valhalla/baldr/transittrip.h

Change method names to *offset (rather than index).

Add constructors with args.

---

src/baldr/graphtile.cc
src/baldr/graphtileheader.cc
valhalla/baldr/graphtile.h
valhalla/baldr/graphtileheader.h

Add arrays of transit data in graph tile.

Add transit counts to header

---

.gitignore
Makefile.am
src/baldr/streetname.cc
src/baldr/streetnames.cc
src/baldr/streetnames_factory.cc
test/streetname.cc
test/streetnames.cc
test/streetnames_factory.cc
valhalla/baldr/streetname.h
valhalla/baldr/streetnames.h
valhalla/baldr/streetnames_factory.h

Added StreetNamesFactory and Implemeneted non-country specific StreetName and StreetNames

---

src/baldr/location.cc
test/location.cc
valhalla/baldr/location.h

Paired with @gknisely 
Fixed address parsing and old tests
Added new tests
@dnesbitt61 @kevinkreiser

Added heading

---

src/baldr/graphtile.cc
valhalla/baldr/graphtile.h

@dgearhart @dnesbitt61 @kevinkreiser

updated to use unique_ptr.

---

src/baldr/location.cc
test/location.cc
valhalla/baldr/location.h

Added FromPtree and associated tests

---

src/baldr/location.cc
test/location.cc
valhalla/baldr/location.h

Added FromJson

---

src/baldr/location.cc
test/location.cc

changed latitude to lat and longitude to lon

---

src/baldr/graphtile.cc
valhalla/baldr/graphtile.h

Calendar additions are added with start_date == end_date and only subtractions
remain in the TransitCalendar records.

Updates to GetNextDeparture based on rules for calendar date exceptions.

---

.gitignore
Makefile.am
src/baldr/graphid.cc
src/baldr/pathlocation.cc
test/json.cc
valhalla/baldr/graphid.h
valhalla/baldr/json.h
valhalla/baldr/pathlocation.h

need it at various stages the move was long overdue. would have rather had it in midgard but it depends on boost::variant and i figured it wasnt worth making midgard have boost dependencies (and it certainly wasnt worth reimplementing variant!)
added some serializing of path location object so that loki can pass those onto thor

move json to baldr from tyr

---

src/baldr/connectivity_map.cc

last connectivity map pull request for now i promise (excluding the one to turn it on in data production chef land of course)

sort geojson connectivity map by largest regions first

---

src/baldr/directededge.cc
src/baldr/nodeinfo.cc
valhalla/baldr/graphconstants.h

No more horsing around.  Bus wins.

added bus.

---

src/baldr/graphtile.cc

Need to move forward when getting departures until departure time is >= current time. Binary search could leave in state where departure < current time.

Fix GetNextDeparture

---

src/baldr/datetime.cc
test/datetime.cc
valhalla/baldr/datetime.h

First step in TimeZone logic.  2 functions added:  Get the iso date and time from a DOW mask and time. Get the iso date and time from the current time.  Test added as well.  
I am thinking that the functions will have to be re-factored to use a tz offset from UTC and not the tz_string.  We will see.....anyhow, like I said first steps.

Time goodies

---

src/baldr/datetime.cc
test/datetime.cc

added support for transitland's date format.
added tests as needed.

added support for transitland's date format.  Updated tests.

---

src/baldr/nodeinfo.cc
valhalla/baldr/graphconstants.h
valhalla/baldr/nodeinfo.h

Driveability -----> Traversability

Traversability

---

src/baldr/graphreader.cc
valhalla/baldr/graphreader.h

this is useful in loki, pr coming

its useful to get the tile (optionally) when getting opposing edge(id)s

---

src/baldr/datetime.cc
src/baldr/directededge.cc
src/baldr/edgeinfo.cc
src/baldr/graphid.cc
src/baldr/nodeinfo.cc
valhalla/baldr/datetime.h
valhalla/baldr/directededge.h
valhalla/baldr/edgeinfo.h
valhalla/baldr/graphconstants.h
valhalla/baldr/graphid.h
valhalla/baldr/nodeinfo.h

this is useful for locate results. the main reason we might want this (at least why i want it) is so that we can far more easily debug issues. knowing how something is attributed is a massive help. ive purposely left a bit of information from both nodes and edges out (not knowing if its useful or visually possibly to determine whats what). anyway we can expand on it at any time.

self serializers for nodes and edges

---

src/baldr/datetime.cc
test/datetime.cc
valhalla/baldr/datetime.h

Added is_iso_local function to validate the date_time that the user sends to loki.  
Added tests.
Date_time_value string will be validated in loki.

is_iso_local function

---

src/baldr/datetime.cc
valhalla/baldr/datetime.h

removed bitset

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h
valhalla/baldr/graphconstants.h

Remove ferry and rail ferry flags from directed edge. 

---

src/baldr/nodeinfo.cc
valhalla/baldr/graphconstants.h

Remove bus and rail node types for now.

---

src/baldr/graphtile.cc
src/baldr/graphtileheader.cc
src/baldr/tilehierarchy.cc
valhalla/baldr/graphtile.h
valhalla/baldr/graphtileheader.h

since we've been calling this edge binning it seemed we should be consistent throughout the projects. this will make mjolnir fail so id only merge it once i have the edge binning branch of mjolnir pr'd and ready

make nominclature match across projects

---

src/baldr/directededge.cc

These are bitwise & operations

Fix JSON output for access and bike network.

---

src/baldr/edgeinfo.cc

uses https://github.com/valhalla/midgard/pull/82

use varint encoding for edges to save some space

---

src/baldr/datetime.cc
test/datetime.cc
valhalla/baldr/datetime.h

return tz offset in getduration

Date fixes

---

src/baldr/transitdeparture.cc

updated to support dup schedule records.

---

src/baldr/directededge.cc
valhalla/baldr/directededge.h

Needed to allow U-turns at dead-ends

Add a flag for a directed edge that ends at a dead-end node.

---

src/baldr/datetime.cc
test/datetime.cc

Removed tz offset and added the tz abbrev to get_duration.

Tz addition

---

src/baldr/directededge.cc
test/directededge.cc
valhalla/baldr/directededge.h

Uses 1 degree precision up to 16 degrees and 4 degrees afterwards (up to max of 76 degrees).

Add max_up_slope and max_down_slope (and set methods).

---

src/baldr/graphtile.cc
valhalla/baldr/graphtile.h

used to include or exclude transit lines.

added onestop maps.

---

src/baldr/directededge.cc
src/baldr/nodeinfo.cc

Check access modes to make sure they do not exceed the max (kAllAccess).

Add output for wheelchair. Validate set access.

---

valhalla/baldr/errorcode_util.h

Forgot to add optional customized error portion to error code message

Error code Message - added customized portion

---

valhalla/baldr/errorcode_util.h

- Added colons after Unknowns since these will most likely be followed by a exception.what() description

Updated error utility for internal errors

---

valhalla/baldr/errorcode_util.h

- 	moved a few of the codes around, renumbered and removed colons from the unknowns
-	combined search errors into 1 error

Internal Error Code Updates

---

src/baldr/pathlocation.cc

@dnesbitt61 maybe this will fix?

casting side of street enum to int

---

valhalla/baldr/edgeinfo.h

Reserve 5 bits for use by forks of Valhalla.

---

src/baldr/graphreader.cc

Return nullptr from GetGraphTile if the tile Id is invalid
