valhalla/baldr

src/baldr/graphtile.cc, valhalla/baldr/graphtile.h
Protect against offsets exceeding the size of the names list.
=> Add method to get names for an edge.

src/baldr/directededge.cc, valhalla/baldr/directededge.h
Will use "speed  cost factors" rather than dividing through by speed.  So don't want to return float
=> Return speed as int

src/baldr/location.cc, test/location.cc
so to match the code i changed the parsing of lat lon to be lon lat but that seems to be not a convention humans use to much. so i'm changing it back. this will change anything that parses strings into `PointLL` objects or `Location` objects.
=> lat, lon parse order

src/baldr/graphtile.cc, valhalla/baldr/graphtile.h
Often we have the shared ptr, so no need to get it again when retrieving names.
=> Add GetNames method that takes the edgeinfo shared ptr. Add comments.

.gitignore, Makefile.am, src/baldr/graphreader.cc, src/baldr/graphtile.cc, test/graphtile.cc, valhalla/baldr/graphtile.h
this makes it so that tiles will be written only 1000 at a time to any single dir and that no dir has no more than 1000 other dirs in it. there is  a test against this as well.
it also does a little clean up of shared pointer stuff and the GetNames function
this breaks mjolnir and thor, prs in the hopper
=> tile uri generation to make sure not too many files in one dir

src/baldr/directededge.cc, src/baldr/graphtile.cc, src/baldr/graphtileheader.cc, valhalla/baldr/directededge.h, valhalla/baldr/graphtile.h, valhalla/baldr/graphtileheader.h
Added GraphId to the GraphTileHeader.
This is a new GetExitSignList method. When it is working the existing exit sign logic (with exits stored on EdgeInfo) will be removed.
=> New exit list logic.

src/baldr/edgeinfo.cc, src/baldr/exitsign.cc, src/baldr/graphtile.cc, src/baldr/graphtileheader.cc, valhalla/baldr/edgeinfo.h, valhalla/baldr/exitsign.h, valhalla/baldr/graphtile.h, valhalla/baldr/graphtileheader.h
Fixed size so store them after directed edges. Store count rather than offset in GraphTileHeader. Remove exit signs from edgeInfo. Signature of getting exit signs from tile remains the same, but they will be accessed via directed edge index (logic for searching is TBD).
=> Move exit signs to be separate entity 

src/baldr/graphreader.cc, src/baldr/graphtile.cc, src/baldr/pathlocation.cc
these were popping up when checking hot spots with callgrind
=> avoid allocating memory over  and avoid reallocating containers on expansion

Makefile.am, src/baldr/directededge.cc, src/baldr/graphtile.cc, src/baldr/graphtileheader.cc, src/baldr/turnrestriction.cc, valhalla/baldr/directededge.h, valhalla/baldr/graphtile.h, valhalla/baldr/graphtileheader.h, valhalla/baldr/turnrestriction.h
A flag on the directed edge indicates the start of a simple turn restriction. A bit mask in the turn restriction record (indexed by the directed edge index) indicates the indexes of directed edges at the end node which are restricted. Turn restriction records are fixed size and stored as an array (ordered by the from directed edge index). A binary search is used to access - here there is only one TR record possible for a directed edge (unlike the sign lookup) which simplifies things.
=> Add support for simple turn restrictions.

valhalla/baldr/directededge.h
- set a max so we can see if it is ever exceeded in tile building.
=> Use 8 bits for turn restriction mask 

test/nodeinfo.cc
Tested this by adding 1 bit to one of the "spare" parts of a struct so it exceeded the 32 bit size.
This caused a test failure - which is what we want.
=> Add test to make sure size of NodeInfo is correct.

src/baldr/directededge.cc, src/baldr/location.cc, valhalla/baldr/directededge.h
Validate and fix lat,lng inputs - throw exception if lng is outside range from -360 to 360 degrees or lat is outside -90 to 90 degrees. Fix longitude to lie within -180 to 180 degrees.
Increase max edge info offsets. Believe there are a few very dense areas in Asia where we don't drop enough edges going from local to arterial.
=> Fixes for Asia

src/baldr/directededge.cc, valhalla/baldr/directededge.h
Any value > max transitions 8 will not be able to look up edge transition information, but we need a value > 8
so a valid value is not used in cases where > 8 edges occur at a node.
=> Needed 4 bits for opposing local index. 

src/baldr/directededge.cc, src/baldr/nodeinfo.cc, test/directededge.cc, test/nodeinfo.cc, valhalla/baldr/directededge.h, valhalla/baldr/graphconstants.h, valhalla/baldr/nodeinfo.h
NodeInfo size increased to 32bytes: added name continuity, headings, and driveability for up to 8 edges (using local edge index to reference).
DirectedEdge size reduce to 40 bytes: added edge_to_left and edge_to_right flags but removed name continuity and spare 64bit word reserved for edge transitions (not needed due to additions to NodeInfo).
=> Updates for edge transitions

src/baldr/directededge.cc, valhalla/baldr/directededge.h
Only kMaxShortcutsFromNode can have a mask and supersede an edge, but more than this # of shortcuts can be stored.
=> Add is_shortcut flag. 

src/baldr/location.cc, test/location.cc
updated tests, removed explicit testing of `FromPtree` since the test was just doing exactly what `FromJson` does, ie. make a ptree and then just call `FromPtree`
=> default to break for location type

src/baldr/graphtile.cc, valhalla/baldr/graphtile.h
Return a const pointer to avoid a copy to the base structure.
=> Update comments for admin methods. 

src/baldr/nodeinfo.cc, valhalla/baldr/nodeinfo.h
Check if the node is a transit stop when returning the stop_id (returns 0 if not a transit stop).
=> Add convenience method "is_transit" 

src/baldr/graphreader.cc, src/baldr/pathlocation.cc, valhalla/baldr/graphreader.h, valhalla/baldr/pathlocation.h
They need to be the incoming edges. Add a way to clear the existing edges and then we can add back the opposing edge Ids in thor when needed.
=> Methods needed to change destination edges at a node

Makefile.am, configure.ac, m4/ax_boost_filesystem.m4, scripts/dependencies.sh, src/baldr/graphreader.cc, src/baldr/graphtile.cc, valhalla/baldr/graphreader.h, valhalla/baldr/graphtile.h
This will allow testing origin and destination to see if a path of populated tiles connects them. We can very quickly reject paths between locations that have no possible connectivity. To handle long ferries we can add "empty" tiles for where the ferry crosses but no end nodes exist.
Also added a method to return the tile Id given the filename (no need to actually open/read the file).
=> Add methods to get a map of populated tiles and a connectivity map.

Makefile.am, src/baldr/connectivity_map.cc, src/baldr/graphreader.cc, src/baldr/graphtile.cc, test/graphreader.cc, valhalla/baldr/connectivity_map.h, valhalla/baldr/graphreader.h, valhalla/baldr/graphtile.h
moved the connectivity map into a singleton in graphgreader. it gets configured once and used everywhere. also changed the reverse mapping of file name string to graphid (was previously hardcoded to be level two with .25 degrees or whatever we have in our configs)
with test yay
=> update connectivity map to be singleton

src/baldr/directededge.cc, src/baldr/graphtile.cc, src/baldr/transitdeparture.cc, valhalla/baldr/directededge.h, valhalla/baldr/graphconstants.h, valhalla/baldr/transitdeparture.h
Store a unique line Id in directed edges and use that rather than the directed edge Id.
Fix a bug with TransitDeparture (used a union rather than struct for ScheduleDates).
Update transit use values to be at the upper end of the range.
=> Fix TransitDeparture and move to using line Id rather than edge Id

valhalla/baldr/json.h
Fixes a compile errror on OpenBSD with boost-1.58:
```
c++ -DHAVE_CONFIG_H -I. -I./valhalla -pthread -I/usr/local/include -Ivalhalla -O2 -pipe -g -std=c++11 -MT src/baldr/libvalhalla_baldr_la-connectivity_map.lo -MD -MP -MF src/baldr/.deps/libvalhalla_baldr_la-connectivity_map.Tpo -c src/baldr/connectivity_map.cc -fPIC -DPIC -o src/baldr/.libs/libvalhalla_baldr_la-connectivity_map.o
In file included from src/baldr/connectivity_map.cc:2:0:
./valhalla/baldr/json.h:32:74: error: 'nullptr_t' was not declared in this scope
using Value = boost::variant<std::string, uint64_t, int64_t, fp_t, bool, nullptr_t, MapPtr, ArrayPtr>;
```
=> Use std::nullptr_t instead of nullptr_t.

src/baldr/graphtile.cc
Was printing node Id twice ratther than tileid.
=> Fix message when node exceeds tile max. 

src/baldr/graphreader.cc, valhalla/baldr/graphreader.h
and protect opposing edge methods from an invalid graph Id (if adjacent tile is empty).
=> Add method to get opposing directed edge 

.gitignore, Makefile.am, src/baldr/verbal_text_formatter_factory.cc, src/baldr/verbal_text_formatter_us.cc, src/baldr/verbal_text_formatter_us_co.cc, src/baldr/verbal_text_formatter_us_tx.cc, test/verbal_text_formatter_us.cc, test/verbal_text_formatter_us_co.cc, test/verbal_text_formatter_us_tx.cc, valhalla/baldr/verbal_text_formatter_us.h, valhalla/baldr/verbal_text_formatter_us_co.h, valhalla/baldr/verbal_text_formatter_us_tx.h
BEFORE (incorrectly calling out Colorado)
Turn left onto Colorado 2 o2.
AFTER
Turn left onto County Road 2 o2.
BEFORE
Turn left onto FM 25 81.
AFTER
Turn left onto Farm to Market Road 25 81.
BEFORE
Turn left to stay on RM 3 37.
AFTER
Turn left to stay on Ranch to Market Road 3 37.
BEFORE
Turn left onto 2nd Street, MO JJ.
AFTER
Turn left onto 2nd Street, Missouri JJ.
BEFORE
Continue on SH 4 70.
AFTER
Continue on State Highway 4 70.
=> Improved TTS for county route/roads, state routes, farm to market roads, and ranch to market roads

.gitignore, Makefile.am
this will create a header `valhalla/baldr/date_time_zonespec.h` from the data found at https://raw.githubusercontent.com/boostorg/date_time/master/data/date_time_zonespec.csv
the header will look like 
unsigned char date_time_zonespec_csv[] = {
0x22, 0x49, 0x44, 0x22, 0x2c, 0x22, 0x53, 0x54, 0x44, 0x20, 0x41, 0x42,
0x42, 0x52, 0x22, 0x2c, 0x22, 0x53, 0x54, 0x44, 0x20, 0x4e, 0x41, 0x4d,
...
0x22, 0x2c, 0x22, 0x22, 0x2c, 0x22, 0x22, 0x2c, 0x22, 0x22, 0x2c, 0x22,
0x2b, 0x30, 0x30, 0x3a, 0x30, 0x30, 0x3a, 0x30, 0x30, 0x22, 0x0a
};
unsigned int date_time_zonespec_csv_len = 35855;
then wherever @gknisely needs to load this data all he must do is loop over this binary data, write it to file, and then send that temp file to boost to load up the timezone stuff. this makes it so we dont have to …
=> add timezone data to a header

src/baldr/graphreader.cc, valhalla/baldr/graphreader.h
Need this for costing origin and destination edges. 
Simplify the GetOpposingEdgeId method.
=> Add method to get relative density at an edge.

valhalla/baldr/graphconstants.h
Now set to ~85MPH. Several places in US and internationally have this speed limit. Have not seen any higher. This has slight impact to A* / performance for driving routes.
=> Increase max speed.

src/baldr/graphtile.cc, valhalla/baldr/graphtile.h
We need this because date can be less than tile_creation date and in MMcosting we were doing the calculation of day = date - tile_creation_date_;  And day is unsigned.  
Thor updates coming as well.
=> added flag to check if the date that was inputed is before the tile_creation date.

src/baldr/graphreader.cc
Since `NO_TILE` is shared globally, it's possible to be changed multiple times during you call `GraphId GraphReader::GetOpposingEdgeId(const GraphId&, const GraphTile*&)` in concurrent and result in out-of-bound issue.
Here is the script to reproduce/verify the issue https://gist.github.com/ptpt/5e07d21bf68f32de7b16
=> Remove the shared variable NO_TILE which causes problems in concurrent

src/baldr/graphid.cc
Fixes a compile error on OpenBSD:
src/baldr/graphid.cc: In member function 'valhalla::baldr::json::Value valhalla::baldr::GraphId::json() const':
src/baldr/graphid.cc:75:22: error: 'nullptr_t' does not name a type
return static_cast<nullptr_t>(nullptr);
^
=> nullptr_t is in the std namespace.

src/baldr/graphtileheader.cc, valhalla/baldr/graphconstants.h, valhalla/baldr/nodeinfo.h
Move kMaxDensity to graphconstants.h so it can be used for both node and tile density.
=> Validate tile header density value.

src/baldr/directededge.cc
(this is used for transition edges and this change makes it so access can be checked on opposing edges to make sure they match (forward against reverse on opposing edge and vice-versa).
=> Also set reverseaccess to all

src/baldr/datetime.cc
Schedule bug.
We were using the start_date set by the transit builder (service_start_date) and not the tile header date.  We should always start from the tile header date and go out 60 days.  
This issue caused the schedule to be off which in turn cause invalid transit routes. 
Old:
2016/02/24 17:18:59.466341 [NARRATIVE] ----------------------------------------------
**2016/02/24 17:18:59.466347 [NARRATIVE] 13: Enter the Babylon station. | 0.0 mi**
2016/02/24 17:18:59.466353 [NARRATIVE]    VERBAL_PRE: Enter the Babylon station.
2016/02/24 17:18:59.466358 [NARRATIVE]    VERBAL_POST: Continue for 100 feet.
2016/02/24 17:18:59.466362 [NARRATIVE] ----------------------------------------------
2016/02/24 17:18:59.466367 [NARRATIVE]    Depart: 12:00 PM from Babylon.
2016/02/24 17:18:59.466372 …
=> schedule fix

src/baldr/transitroute.cc, valhalla/baldr/graphconstants.h, valhalla/baldr/transitroute.h
routeid not needed.  using this space to set the route_type now.  
Also, checked in a missing header updated from date_time.
=> routeid --> route_type 

src/baldr/graphreader.cc
Return an invalid GraphId when getting the opposing edge of a transit line. These do not have proper opposing edges assigned yet.
=> GetOpposingEdgeId - return invalid GraphId for transit lines

Makefile.am, src/baldr/graphtile.cc, src/baldr/graphtileheader.cc, src/baldr/transitdeparture.cc, src/baldr/transitschedule.cc, valhalla/baldr/graphconstants.h, valhalla/baldr/graphtile.h, valhalla/baldr/graphtileheader.h, valhalla/baldr/transitdeparture.h, valhalla/baldr/transitschedule.h
Add a structure to store unique schedule validity periods. 
Replace TransitTransfer (unused) with the new TransitSchedule structure within tiles.
Separate transit schedule information from transit departures and index into the new TransitSchedule records. 
Compress TransitDeparture to get down to 20 bytes per departure (was 32).
Check max. values and throw exceptions when exceeded.
=> TransitDeparture Rework

src/baldr/edgeinfo.cc
when we had visible ascii shape and it was compressed in the `edgeinfo`, then the `loki::locate` action could just use it directly. but now its in a more compact format. so to return it we must decode it and reencode it.
=> need to reencode to visible ascii

src/baldr/connectivity_map.cc, src/baldr/graphtile.cc, valhalla/baldr/graphtile.h
Should allow this to be used by transit tiles.
=> Send in tile directory to GetTileId (rather than TileHierarchy).

src/baldr/connectivity_map.cc, valhalla/baldr/connectivity_map.h, valhalla/baldr/json.h
before the geojson output was points and was not great for efficiency nor display. now its polygons which is far easier to use.
caveat, i havent yet implemented the inner rings of the polygons and therefore you may see two different connectivity regions (specifically smaller ones inside of big ones) that touch eachother. This is because one of them is inside of a missing inner ring of another one. i'll get that in another pr.
ive also styled the geojson so that it displays nicely on geojson.io. once these are up on s3 we can use geojson.ios api to display the latest ones directly from a github.io page. i'll hack that together at some point..
=> connectivity map as polygons instead of point clouds

src/baldr/connectivity_map.cc, src/baldr/graphreader.cc, src/baldr/pathlocation.cc, test/graphreader.cc, valhalla/baldr/connectivity_map.h, valhalla/baldr/graphreader.h, valhalla/baldr/pathlocation.h
this refactors connectivity map lookups out of graph reader because the way in which loki will use it is changing.
it also refactors pathlocation so that loki can more easily have multiple matches (for islands but also for fuzzy matching and other improvements related to search scoring)
=> refactor for fuzzy connectivity map and loki islands multiple results

src/baldr/datetime.cc, test/datetime.cc, valhalla/baldr/datetime.h, valhalla/baldr/graphconstants.h
Clean up.
When a route crosses the beginning or end of dst, we should adjust the time correctly.
Added lots of tests.
=> Date fixes

src/baldr/transitdeparture.cc, valhalla/baldr/graphconstants.h
Will allow us to work with bit fields to allow higher elapsed time values.
=> Set maximum values for trip Id and headsign offset.

src/baldr/graphtile.cc, valhalla/baldr/graphtile.h
This is called from the Initialize method if the tile is a transit tile. This was not in prior MMAP logic, now this works for both mmap and file I/O.
=> Add method to associate onestop Ids.

src/baldr/graphtile.cc, valhalla/baldr/graphtile.h
instead of spooling back to the beginning to get the first matching record ive slightly modified the 4 binary searches to find the first matching record. ive also simplified the logic after each one for the various other criteria.
in addition to that when asking for the next departure you can also specify that you need one that supports bike and/or wheelchair
=> make binary search faster, add wheelchair and bike to departure lookup

src/baldr/connectivity_map.cc, src/baldr/graphreader.cc, test/graphreader.cc, valhalla/baldr/connectivity_map.h, valhalla/baldr/graphreader.h, valhalla/baldr/tilehierarchy.h
so connectivity map was broken because it rolled its own t hing for looking at what tiles we have. this is the first step to making graphreader the sole controller of knowing where tiles are (for reading at least). ive added a comment to tilehierarchy for the rest of the work but it has a lot of side effects so i climbed back out of that rabbit hole for now.
=> graphreader is the arbitor of tiles

src/baldr/edgeinfo.cc, src/baldr/geojson.cc
dont copy the encoded linestring when decoding it, this is an effort to provide an alternative to #298 as outlined by @TeXitoi
=> dont copy the shape bytes into a string to decode them

src/baldr/pathlocation.cc
This avoids roundoff that was leading to shape issues.
fixes valhalla/loki#162
=> Serialize the projected lat,lon as double.

.gitignore, Makefile.am, src/baldr/graphreader.cc, src/baldr/merge.cc, src/merge.cpp, test/edgecollapser.cc, valhalla/baldr/graphid.h, valhalla/baldr/merge.h
This adds a function `valhalla::baldr::merge` which takes a `GraphReader` and a functor, and iterates over all the edges in the graph to find those which are collapsible, calling the functor for each collapsed set of edges.
This is a building block for OpenLR-like descriptors, and intended to group edges into sequences where there are no true intersections, but there might be bridges or changes in other properties such as max speed.
@kevinkreiser could you take a look and let me know what you think, please?
=> Add edge merging

src/baldr/graphtileheader.cc, valhalla/baldr/graphtileheader.h
rather than an entry in the empty_slots array. Turns out that if you add new entries the slot in empty_tiles
used to set the end offset changes position in the header, so an old tile end offset is going to be 0. This makes sure the end offset is always at the end of the graph tile header.
=> Explicitly set end_offset_ as its own data member 

src/baldr/directededge.cc, src/baldr/double_bucket_queue.cc, src/baldr/graphid.cc, src/baldr/graphtileheader.cc, src/baldr/nodeinfo.cc, src/baldr/tilehierarchy.cc, valhalla/baldr/directededge.h, valhalla/baldr/double_bucket_queue.h, valhalla/baldr/graphid.h, valhalla/baldr/graphtileheader.h, valhalla/baldr/nodeinfo.h
This leads to a good performance improvement. Also, go back to using empty_slots[0] for the end of tile
offset, but set all epty slots to the end offset value so that different data versions and code still work.
=> Move most "get" methods to .h files. 

src/baldr/merge.cc, test/edgecollapser.cc, valhalla/baldr/errorcode_util.h
NOTE: this is a merge into the segments branch, not master.
The loop which was exploring edges was testing the mark on "seen" edges, which meant that it would see the mark it just made and assume that the edge could not be explored. Checking the mark is necessary before starting to explore a node, to ensure that edges are not explored twice. However, in the exploration loop it is not required, and prevents segments of longer than length 2 being created.
I've added a simple test case for this as well.
@dnesbitt61 could you review, please?
=> Merged master and fixed a bug

src/baldr/directededge.cc, valhalla/baldr/directededge.h
Separate spare from the endnode so we can actually use the spare bits in GraphId.
=> Add named flag. 

src/baldr/graphreader.cc, src/baldr/tilehierarchy.cc, test/graphreader.cc, valhalla/baldr/edgeinfo.h
Since tile extent can be configurable it doesn't make sense to normalize lat,lon if out or normal ranges.
Fixes #334
=> Return nullptr from GetGraphTile if lat,lon is out of range

src/baldr/tilehierarchy.cc, test/tilehierarchy.cc, valhalla/baldr/tilehierarchy.h
Add a couple of convenient functions to `TileHierarchy` to return the IDs of tiles which intersect given bounding boxes at some or all levels.
@kevinkreiser could you review, please?
=> Add bounding-box based "GetTiles" to TileHierarchy

src/baldr/datetime.cc
fixed a issue where date and time was returning an invalid ISO8601 time format for date_time values in positive UTC.  + was missing.
Tested NYC, London, and Berlin.
Fixes valhalla/valhalla#13
=> invalid ISO8601 time format for + UTC

Makefile.am, src/baldr/graphtile.cc, src/baldr/trafficassociation.cc, valhalla/baldr/graphtile.h, valhalla/baldr/trafficassociation.h
Use less memory for the most common case: a 1:1 edge to segment association where the segment is in the same tile as the edge. Also update the TrafficChunk structure. Add a new structure, TrafficSegment, to return from the graph tile.
=> Updates to TrafficAssociation structures
